### ISSUE TITLE
No labels on Extended List Widget for TV Channels

### ISSUE THREAD

**Issue by bartolomesoriano** [MadMikeDoc/skin.aeon.madnox#109]
The list is scrollable, but there are no labels for the items in the list.  Please see http://forum.kodi.tv/showthread.php?tid=230821&pid=2266440#pid2266440.

**Comment by ghost** [comment]
Affects all widget layouts, not just list.

Looked at the source code for this widget (provided by Skin Helper Service). Channel name is ListItem.Property(channel), current program is ListItem.Title. ListItem.Label is empty.

@mistervee - sounds like specific support should be added, but the widgets have got just that bit too complex for me to know what to edit to get the channel name in the standard label.

**Comment by mistervee** [comment]
Now Fixed and committed to master.

Just an error in the way the content was specified in the overrides.xml
