### ISSUE TITLE
Temperature units show twice in system info widget (Graphics, CPU)

### ISSUE THREAD

**Issue by bartolomesoriano** [MadMikeDoc/skin.aeon.madnox#111]
The unit (C, F) shows twice in each of the system info widget items that have a temperature (graphics, cpu).  See http://forum.kodi.tv/showthread.php?tid=230821&pid=2266514#pid2266514.

**Comment by schimi2k** [comment]
i was so brave and just add the tips from bob - we will see if now someone complain about missing cpu units - in this case i will undo this changes again

**Comment by mistervee** [comment]
Looks good.
