### ISSUE TITLE
Edge of Fanart image visible in KodiFlix with Small Fanart Option Enabled

### ISSUE THREAD

**Issue by bartolomesoriano** [MadMikeDoc/skin.aeon.madnox#114]
In the KodiFlix view if you use the small fanart option, there no longer seems to be a proper fade between the background fanart and the logo/info so you can clearly see the edges of the image. 

See http://forum.kodi.tv/showthread.php?tid=230821&pid=2266336#pid2266336

**Comment by MadMikeDoc** [comment]
corrected in next push.
