### ISSUE TITLE
Small empty rectangle visible in upper left corner when Intro video disabled

### ISSUE THREAD

**Issue by bartolomesoriano** [MadMikeDoc/skin.aeon.madnox#115]
There is a small empty rectangle visible briefly when you start Kodi, in the upper left hand corner of the screen.  This is shown when you have the intro video disabled.  See: http://forum.kodi.tv/showthread.php?tid=230821&pid=2266343#pid2266343.

**Comment by schimi2k** [comment]
it seems the issue is somewhere in startup.xml : 
`<control type="button" id="10">
            <onfocus condition="Skin.HasSetting(Use_Startup_Playlist) + !IsEmpty(Skin.String(Startup_Playlist_Path)) + !SubString(Skin.String(Startup_Playlist_Path),RunScript,left)">PlayMedia($ESCINFO[Skin.String(Startup_Playlist_Path)])</onfocus>
            <onfocus condition="Skin.HasSetting(Use_Startup_Playlist) + !IsEmpty(Skin.String(Startup_Playlist_Path)) + SubString(Skin.String(Startup_Playlist_Path),RunScript,left)">$ESCINFO[Skin.String(Startup_Playlist_Path)]</onfocus>
            <onfocus>SetFocus(11)</onfocus>
            <onclick>noop</onclick>
        </control>`
when i disable this "button" i dont get the flashing rectangle anymore - but its also stucked on loading screen - when i try to hide it, or resize it it doesnt work...
maybe someone else have an idea ( well, someone with coding skills hehe )

**Comment by MikeSiLVO** [comment]
@schimi2k Try adding the HiddenObject include to buttons 10 and 11 :wink: 

```
<control type="button" id="10">
    <include>HiddenObject</include>
    <onfocus condition="Skin.HasSetting(Use_Startup_Playlist) + !IsEmpty(Skin.String(Startup_Playlist_Path)) + !SubString(Skin.String(Startup_Playlist_Path),RunScript,left)">PlayMedia($ESCINFO[Skin.String(Startup_Playlist_Path)])</onfocus>
    <onfocus condition="Skin.HasSetting(Use_Startup_Playlist) + !IsEmpty(Skin.String(Startup_Playlist_Path)) + SubString(Skin.String(Startup_Playlist_Path),RunScript,left)">$ESCINFO[Skin.String(Startup_Playlist_Path)]</onfocus>
    <onfocus>SetFocus(11)</onfocus>
    <onclick>noop</onclick>
</control>
<control type="button" id="11">
    <include>HiddenObject</include>
    <onup>ReplaceWindow($INFO[System.StartupWindow])</onup>
    <ondown>ReplaceWindow($INFO[System.StartupWindow])</ondown>
    <onleft>ReplaceWindow($INFO[System.StartupWindow])</onleft>
    <onright>ReplaceWindow($INFO[System.StartupWindow])</onright>
    <onclick>ReplaceWindow($INFO[System.StartupWindow])</onclick>
    <onfocus>ReplaceWindow($INFO[System.StartupWindow])</onfocus>
    <animation effect="fade" start="100" end="0" time="7500">Focus</animation>
</control>
```

**Comment by schimi2k** [comment]
i swear to donald trump and to god !!!
i have try this <include>HiddenObject</include> - but just on id10 !
with both it is fixed !!!
thx master silvo :)

**Comment by MikeSiLVO** [comment]
You probably could've also just removed the animation fade include on the common/white.png image as well :smiley:

**Comment by schimi2k** [comment]
jajajajajja... my last plan was to add a black image on top ... 
but this is more professional ;)

**Comment by MikeSiLVO** [comment]
That image control with the white.png below button 11 is a black image over the buttons it's just that you have a fade in time of 200 ms so for that brief moment when you see them is before that black background slowly fades in.

**Comment by schimi2k** [comment]
I had change this also to black before - and without fade etc... But with this actual fix its beautiful... But normaly nobody should see this... Disable my intro is a crime hehe...

**Comment by MikeSiLVO** [comment]
It is a crime indeed, perhaps corporal punishment for such an offense? :wink:
