### ISSUE TITLE
Artist Image not sized properly on magazine widget in Music Vosualization

### ISSUE THREAD

**Issue by bartolomesoriano** [MadMikeDoc/skin.aeon.madnox#117]
When magazine is open, the image does not cover the whole space, as it does when the magazine is closed.

See: http://forum.kodi.tv/showthread.php?tid=230821&pid=2266089#pid2266089.

**Comment by meowmoo** [comment]
its supposed to look like this
like  #118 im not gonna change it 
@MadMikeDoc do it or close it :P

**Comment by MadMikeDoc** [comment]
I'll leave it open but that's only while I think about those music viz widgets. They are a pain and might get looked at, when I've no idea!

**Comment by MadMikeDoc** [comment]
Is as supposed to be.
