### ISSUE TITLE
Panel with next tracks partially covers magazine widget in music visualization

### ISSUE THREAD

**Issue by bartolomesoriano** [MadMikeDoc/skin.aeon.madnox#118]
See: http://forum.kodi.tv/showthread.php?tid=230821&pid=2265908#pid2265908.

**Comment by meowmoo** [comment]
like i told him in the Forum im not gonna do it http://forum.kodi.tv/showthread.php?tid=230821&pid=2266828#pid2266828
i leave this open for @MadMikeDoc  if you not gonna do it close it pls

**Comment by bartolomesoriano** [comment]
Should this be closed?
