### ISSUE TITLE
No cast on next aired widget info panel

### ISSUE THREAD

**Issue by bartolomesoriano** [MadMikeDoc/skin.aeon.madnox#122]
See: http://forum.kodi.tv/showthread.php?tid=230821&pid=2265838#pid2265838.

**Comment by mistervee** [comment]
Will be fixed with this;

https://github.com/MadMikeDoc/skin.aeon.madnox/issues/119

**Comment by mistervee** [comment]
Fixed
https://github.com/MadMikeDoc/skin.aeon.madnox/commit/20e9bfa15c392adda2f39c8bdd5701ece8ae90c5
