### ISSUE TITLE
Resume and New Badges not showing up in ShowCase view

### ISSUE THREAD

**Issue by bartolomesoriano** [MadMikeDoc/skin.aeon.madnox#123]
This seems to be a Linux-only issue.  See: http://forum.kodi.tv/showthread.php?tid=230821&pid=2265858#pid2265858.

**Comment by bartolomesoriano** [comment]
meowmoo provided a solution here: http://forum.kodi.tv/showthread.php?tid=230821&pid=2266780#pid2266780

**Comment by ghost** [comment]
As Windows isn't case sensitive, you'll likely need to use the command line and [git mv](https://git-scm.com/docs/git-mv) to change the filenames.

`git mv -f fileNAME.ext FILEname.EXT`

**Comment by meowmoo** [comment]
Ah, thanks i will put it in my how to git text file for the next time :>

delete push add back in push works also but its dirty....
