### ISSUE TITLE
Text too long on some positions (overlapping)

### ISSUE THREAD

**Issue by schimi2k** [MadMikeDoc/skin.aeon.madnox#126]
on some positions or on some info windows the text is too long and overlap the image

**Comment by schimi2k** [comment]
i fix the first overlapping text i found here:
DialogYesNo.xml
when you try to delete a movie from library 

maybe more...

**Comment by bartolomesoriano** [comment]
@schimi2k Have you been able to find any more? @MadMikeDoc @meowmoo should we close this issue?
