### ISSUE TITLE
"Poster" toggle in List view options does not work at an Episode level

### ISSUE THREAD

**Issue by bartolomesoriano** [MadMikeDoc/skin.aeon.madnox#128]
When using List view at an Episode level for TV Shows, the "Poster" toggle in the view options does not work.  It always shows the season poster,, whether the toggle is On or Off.

See: http://forum.kodi.tv/showthread.php?tid=230821&pid=2268795#pid2268795.

**Comment by schimi2k** [comment]
and the media icons under the poster are moving to the right, when SLIM LIST is activated 
this result in a cut off mpaa icon ( and doesnt need to move )

**Comment by MadMikeDoc** [comment]
There is no code in List to show anything when Poster is disabled. I have corrected the toggle show it shows nothing and also corrected the media icons. It will take time to code thumbs are something else when Poster is off. Will be in next commit from me
