### ISSUE TITLE
No CD Handwriting in AltViz1

### ISSUE THREAD

**Issue by KevinSartori** [MadMikeDoc/skin.aeon.madnox#132]
In Alternate Music Music Visualisation 1, there is no handwritten text on the blank disc.  It is visible when switching to either the default layout or AltViz2.

Also, this is more of a request, but I've noticed that in the main interface, the blank CD "styles" rotate during playback.  Is there any way to add and rotate these different blank CD brands in the visualization?

Thanks!

**Comment by meowmoo** [comment]
960024a
