### ISSUE TITLE
Cannot move away from cast in oninfo panel for widgets

### ISSUE THREAD

**Issue by bartolomesoriano** [MadMikeDoc/skin.aeon.madnox#133]
When showing the oninfo panel for a widget item, if I press down I can access the cast, and I can traverse through the cast pressing left and right. What I cannot do now is go back to the buttons on the panel by pressing up. This happens on all widgets that have a cast, when cast on widgets is enabled.

**Comment by mistervee** [comment]
I'll push a fix within the next day.

**Comment by bartolomesoriano** [comment]
Fixed a while ago by Mr. V.  Closing issue.
