### ISSUE TITLE
Viewtype setting issue

### ISSUE THREAD

**Issue by MadMikeDoc** [MadMikeDoc/skin.aeon.madnox#134]
Hi

Can someone please check viewtype settings for Banner Info and tell me if they get stuck when trying to down to 'Use Logo on Movie Sets'?

I'm trying to add some new controls but nothing is working and I'm a little be miffed right now! No new controls work they all stick on down but I can't find a duplicate id anywhere in and xml so no idea what is going wrong right now!!

**Comment by ghost** [comment]
Duplicate ID 17095 ;)

**Comment by meowmoo** [comment]
Than it was me :(

Just picked the next ID Nr. Did not check for duplicate. 

Will there be a sideeffect if we change them to something like viewnr01, list view would be 5001, rightlist 70501

So it would be easy to add new options And keep track of the used ids

**Comment by MadMikeDoc** [comment]
I have no idea, from read in on the id you are supposed to be able to use what you want so yes that should be possible, but given the age of the skin I have no idea what id's have been used in the past?

**Comment by meowmoo** [comment]
If this duplicate Id issue is only per file I don't see a big problem, if its skin wide we could check the ids with the skintool from phil65 I guess?

**Comment by MadMikeDoc** [comment]
It's skin wide, you cannot use the same Id anywhere. Haven't used Phils skintool for a while so can't recall if this checks ids or not?

**Comment by MadMikeDoc** [comment]
And Thanks Bob, couldn't see the wood for the trees last night!!!

**Comment by ghost** [comment]
I've always believed - and a quick search of the [Kodi forums](http://forum.kodi.tv/showthread.php?tid=176507) agrees - that you can re-use an ID in a different window, it's just in any single window that each ID must be unique.

(And you're welcome - I know what it's like to get code-blindness.)

**Comment by meowmoo** [comment]
Thanks again bob!

So let's change the ids in the viewtyp setting to viewidxx?
