### ISSUE TITLE
ListView No Posters when "rounded covers" are disabled

### ISSUE THREAD

**Issue by schimi2k** [MadMikeDoc/skin.aeon.madnox#135]
There are no Posters shown when "Rounded Covers" are disabled

tested on 2x win10 kodis and 1x openelec kodi - latest madnox 

EDIT:
after i compare the new file with an older one, i found this 2 lines at 1210 & 1281:
`<visible>Skin.HasSetting(ListCase) + Skin.HasSetting(listshowposter)</visible>`

when i change them to:
`<visible>Skin.HasSetting(ListCase)</visible>`
the hardcorner posters working again 

maybe one coder can confirm this ? 
thx

**Comment by schimi2k** [comment]
seems like a bad "EIS" ... maybe i use the master git version of it, and after i review phils kodi forum thread, his master branch is now for krypt...

**Comment by meowmoo** [comment]
Same here, with repo eis...

**Comment by schimi2k** [comment]
try to delete the old one ( and the one inside the package folder ! ) and download it again from repo
that helped me here

**Comment by bartolomesoriano** [comment]
Should we close this issue then @schimi2k @meowmoo?

**Comment by MadMikeDoc** [comment]
This should be fixed now, I found issue in view List with rounded and fixed it, so I'll close it now.
